优化一下
matrixorigin/mlops-images pull request #6
Opened 2024-08-28 15:28 UTC by Sherlocktein

2024-08-31 14:46 UTC, randomradio requested changes

2024-08-31 14:46 UTC, randomradio commented on comfyui/Dockerfile
> +# 启动服务
`../common/init ./init`文件夹里的init脚本需要copy到docker中，并且优先跑
CMD['bash', '这里填入init.sh的路径']
可以参考ollama的镜像

2024-09-02 05:38 UTC, Sherlocktein commented
ubuntu based ComfyUI docker image build scripts.

2024-09-04 14:20 UTC, randomradio approved these changes

2024-09-04 14:20 UTC, merged